# PROLOGUE.sql

CREATE USER 'MACRO{TEST_USER}'@'%' IDENTIFIED BY 'MACRO{TEST_PASSWORD}'
GRANT ALL ON `MACRO{SCHEMA_ONE}`.* TO 'MACRO{TEST_USER}'@'%';
GRANT ALL ON `MACRO{SCHEMA_TWO}`.* TO 'MACRO{TEST_USER}'@'%';
GRANT ALL ON `MACRO{SCHEMA_THREE}`.* TO 'MACRO{TEST_USER}'@'%';

